### ISSUE TITLE
Erro fatal ao realizar busca entre os pré-cadastrados

### ISSUE THREAD

**Issue by ghost** [redelinux-ime-usp/supermegazord#1]

**Comment by danielkza** [comment]
Qual é a mensagem de erro?

**Comment by ghost** [comment]
Mudei o título para ser mais específico.
Esse erro acontece assim que é digitada a primeira letra na busca, mas por algum motivo não ocorre com a letra "a".

```
Traceback (most recent call last):
  File "/opt/bin/supermegazord", line 25, in <module>
    call_curses_interface(None)
  File "/opt/bin/supermegazord", line 21, in call_curses_interface
    cursescli.Run()
  File "/opt/supermegazord/client/newcurses/curse_client.py", line 416, in Run
    curses.wrapper(main)
  File "/usr/local/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/opt/supermegazord/client/newcurses/curse_client.py", line 412, in main
    redraw = current_screen.update(c)
  File "/opt/supermegazord/client/newcurses/curse_client.py", line 127, in update
    return self.filter_addchar(c)
  File "/opt/supermegazord/client/newcurses/curse_client.py", line 120, in filter_addchar
    self.filter_data()
  File "/opt/supermegazord/client/newcurses/curse_client.py", line 103, in filter_data
    self.data = filter(self.filter_item, self.original_data)
  File "/opt/supermegazord/client/newcurses/curse_client.py", line 205, in filter_item
    return regexp.search(item['login']) or regexp.search(item['nid']) or regexp.search(jupinfo.nome)
AttributeError: 'NoneType' object has no attribute 'nome'
```

**Comment by danielkza** [comment]
Pelo jeito existe algum usuário que foi cadastrado mas não está no jupinfo.

**Comment by ghost** [comment]
Yep, era isso mesmo. Haviam alguns usuários sem nome (n/a) entre os pré-cadastrados, bastou excluí-los e a busca começou a funcionar normalmente.

Agora, como eles conseguiram ser pré-cadastrados é um mistério...
